app = "wedding-web"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[mounts]
  source="mysqldata"
  destination="/wedding"

[env]
  MYSQL_DATABASE = "wedding-db"
  MYSQL_USER = "us"

[build]
  image = "mysql:8"

[experimental]
  cmd = [
    "--default-authentication-plugin", 
    "mysql_native_password", 
    "--datadir", 
    "/wedding/mysql"
  ]

[[services]]
  internal_port = 3306
  protocol = "tcp"

[[services.ports]]
  handlers = ["http"]
  port = 3306

